# Generated by Django 2.2.7 on 2019-11-30 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('message', models.TextField()),
                ('participants', models.ManyToManyField(blank=True, related_name='schedule', to='patients.Contact')),
            ],
        ),
    ]
