# Generated by Django 2.2.6 on 2019-10-09 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_insurance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('message', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('physician_name', models.CharField(max_length=100)),
                ('visit_start_time', models.TimeField()),
                ('visit_end_time', models.TimeField()),
                ('message', models.TextField()),
                ('visit_total_charge', models.FloatField()),
                ('visit_total_paid', models.FloatField()),
                ('report_date', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Appointment')),
            ],
        ),
    ]
