# Generated by Django 2.2.7 on 2019-11-16 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='owner',
        ),
    ]
