# Generated by Django 2.1.5 on 2019-09-16 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190915_1657'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
    ]
